import matplotlib.pyplot as plt
import pandas as pd

def table(data_list: list, name: str):
    data_list_size = len(data_list)
    for i  in range(data_list_size):
        data_dict = data_list[i]

        object_labels = []
        hand_labels = []
        event_labels = []
        hand_scores = []
        n = 0
        for k in data_dict:
            print(k)
            object_labels.append(k)
            print(object_labels)
            event_dict = data_dict[k]
            for k, v in event_dict.items():
                print(k,v)
                event_labels.append(k)
                hand_dict = event_dict[k]
                for k, v in hand_dict.items():
                    if n == 0:
                        hand_labels.append(k)
                    print(k, v)
                    hand_scores.append(v)
                n += 1

        print(object_labels)
        print(event_labels)
        print(hand_labels)
        print(hand_scores)
        print(hand_scores[:3], hand_scores[3:6], hand_scores[6:9], hand_scores[9:12])


        d = {event_labels[0]: hand_scores[:3],
            event_labels[1]: hand_scores[3:6],
            event_labels[2]: hand_scores[6:9], 
            event_labels[3]: hand_scores[9:12]}
        row = hand_labels
        df = pd.DataFrame(d, index= row)


            # scores.append(v)

        # data = []
        # df = pd.DataFrame(data)
        fig, ax = plt.subplots(figsize=(3, 3))
        ax.axis("off") 
        ax.axis("tight")

        ax.table(cellText=df.values, colLabels= df.columns, bbox=[0, 0, 1, 1], rowLabels = df.index)
        # object_labels[0] = object_labels[0].split("_")[0]
        if name == "tanakaAver2":
            title = "User2 A"

        elif name == "nishiAver2":
            title = "User1 A"

        elif name == "nishiBver2":
            title = "User1 B"

        elif name == "tanakaBver2":
            title = "User2 B"

        else:
            title = "None"
        plt.title('{} {}'.format(title, object_labels[0].split("_")[0]))
        plt.show()
    return

# data_list_nishiA = [{'Slate_Word4': {'HoverExit': {'RHand(Direct)': 10, 'LHand(DIrect)': 0, 'times': 10}, 'HoverEnter': {'RHand(Direct)': 10, 'LHand(DIrect)': 0, 'times': 10}, 'SelectEnter': {'RHand(Direct)': 0, 'LHand(DIrect)': 0, 'times': 0}, 'SelectExit': {'RHand(Direct)': 6, 'LHand(DIrect)': 0, 'times': 6}}}, {'Booze_Word8': {'HoverExit': {'RHand(Direct)': 6, 'LHand(DIrect)': 2, 'times': 8}, 'HoverEnter': {'RHand(Direct)': 4, 'LHand(DIrect)': 2, 'times': 6}, 'SelectEnter': {'RHand(Direct)': 0, 'LHand(DIrect)': 0, 'times': 0}, 'SelectExit': {'RHand(Direct)': 3, 'LHand(DIrect)': 1, 'times': 4}}}, {'Persimmon_Word1': {'HoverExit': {'RHand(Direct)': 9, 'LHand(DIrect)': 0, 'times': 9}, 'HoverEnter': {'RHand(Direct)': 8, 'LHand(DIrect)': 1, 'times': 9}, 'SelectEnter': {'RHand(Direct)': 0, 'LHand(DIrect)': 0, 'times': 0}, 'SelectExit': {'RHand(Direct)': 9, 'LHand(DIrect)': 0, 'times': 9}}}, {'Talisman_Word10': {'HoverExit': {'RHand(Direct)': 5, 'LHand(DIrect)': 2, 'times': 7}, 'HoverEnter': {'RHand(Direct)': 5, 'LHand(DIrect)': 2, 'times': 7}, 'SelectEnter': {'RHand(Direct)': 0, 'LHand(DIrect)': 0, 'times': 0}, 'SelectExit': {'RHand(Direct)': 5, 'LHand(DIrect)': 0, 'times': 5}}}, {'Canine_Word3': {'HoverExit': {'RHand(Direct)': 14, 'LHand(DIrect)': 1, 'times': 15}, 'HoverEnter': {'RHand(Direct)': 12, 'LHand(DIrect)': 3, 'times': 15}, 'SelectEnter': {'RHand(Direct)': 0, 'LHand(DIrect)': 0, 'times': 0}, 'SelectExit': {'RHand(Direct)': 6, 'LHand(DIrect)': 0, 'times': 6}}}, {'Snail_Word2': {'HoverExit': {'RHand(Direct)': 7, 'LHand(DIrect)': 0, 'times': 7}, 'HoverEnter': {'RHand(Direct)': 7, 'LHand(DIrect)': 0, 'times': 7}, 'SelectEnter': {'RHand(Direct)': 0, 'LHand(DIrect)': 0, 'times': 0}, 'SelectExit': {'RHand(Direct)': 7, 'LHand(DIrect)': 0, 'times': 7}}}, {'Crate_Word6': {'HoverExit': {'RHand(Direct)': 4, 'LHand(DIrect)': 1, 'times': 5}, 'HoverEnter': {'RHand(Direct)': 4, 'LHand(DIrect)': 1, 'times': 5}, 'SelectEnter': {'RHand(Direct)': 0, 'LHand(DIrect)': 0, 'times': 0}, 'SelectExit': {'RHand(Direct)': 3, 'LHand(DIrect)': 0, 'times': 3}}}, {'Pottery_Word5': {'HoverExit': {'RHand(Direct)': 10, 'LHand(DIrect)': 2, 'times': 12}, 'HoverEnter': {'RHand(Direct)': 8, 'LHand(DIrect)': 4, 'times': 12}, 'SelectEnter': {'RHand(Direct)': 0, 'LHand(DIrect)': 0, 'times': 0}, 'SelectExit': {'RHand(Direct)': 8, 'LHand(DIrect)': 0, 'times': 8}}}, {'Fluff_Word7': {'HoverExit': {'RHand(Direct)': 3, 'LHand(DIrect)': 3, 'times': 6}, 'HoverEnter': {'RHand(Direct)': 3, 'LHand(DIrect)': 3, 'times': 6}, 'SelectEnter': {'RHand(Direct)': 0, 'LHand(DIrect)': 0, 'times': 0}, 'SelectExit': {'RHand(Direct)': 3, 'LHand(DIrect)': 1, 'times': 4}}}, {'Fungus_Word9': {'HoverExit': {'RHand(Direct)': 1, 'LHand(DIrect)': 1, 'times': 2}, 'HoverEnter': {'RHand(Direct)': 0, 'LHand(DIrect)': 0, 'times': 0}, 'SelectEnter': {'RHand(Direct)': 0, 'LHand(DIrect)': 0, 'times': 0}, 'SelectExit': {'RHand(Direct)': 0, 'LHand(DIrect)': 0, 'times': 0}}}]
# data_list_nishiB = [{'Carving_Word5': {'HoverExit': {'RHand(Direct)': 10, 'LHand(DIrect)': 1, 'times': 11}, 'HoverEnter': {'RHand(Direct)': 8, 'LHand(DIrect)': 2, 'times': 10}, 'SelectEnter': {'RHand(Direct)': 0, 'LHand(DIrect)': 0, 'times': 0}, 'SelectExit': {'RHand(Direct)': 9, 'LHand(DIrect)': 1, 'times': 10}}}, {'Granite_Word4': {'HoverExit': {'RHand(Direct)': 9, 'LHand(DIrect)': 2, 'times': 11}, 'HoverEnter': {'RHand(Direct)': 9, 'LHand(DIrect)': 2, 'times': 11}, 'SelectEnter': {'RHand(Direct)': 0, 'LHand(DIrect)': 0, 'times': 0}, 'SelectExit': {'RHand(Direct)': 3, 'LHand(DIrect)': 0, 'times': 3}}}, {'Decor_Word10': {'HoverExit': {'RHand(Direct)': 0, 'LHand(DIrect)': 0, 'times': 0}, 'HoverEnter': {'RHand(Direct)': 0, 'LHand(DIrect)': 0, 'times': 0}, 'SelectEnter': {'RHand(Direct)': 0, 'LHand(DIrect)': 0, 'times': 0}, 'SelectExit': {'RHand(Direct)': 0, 'LHand(DIrect)': 0, 'times': 0}}}, {'Garland_Word6': {'HoverExit': {'RHand(Direct)': 8, 'LHand(DIrect)': 0, 'times': 8}, 'HoverEnter': {'RHand(Direct)': 8, 'LHand(DIrect)': 0, 'times': 8}, 'SelectEnter': {'RHand(Direct)': 0, 'LHand(DIrect)': 0, 'times': 0}, 'SelectExit': {'RHand(Direct)': 3, 'LHand(DIrect)': 0, 'times': 3}}}, {'Ewe_Word2': {'HoverExit': {'RHand(Direct)': 21, 'LHand(DIrect)': 3, 'times': 24}, 'HoverEnter': {'RHand(Direct)': 21, 'LHand(DIrect)': 3, 'times': 24}, 'SelectEnter': {'RHand(Direct)': 0, 'LHand(DIrect)': 0, 'times': 0}, 'SelectExit': {'RHand(Direct)': 7, 'LHand(DIrect)': 0, 'times': 7}}}, {'Dandelion_Word9': {'HoverExit': {'RHand(Direct)': 2, 'LHand(DIrect)': 0, 'times': 2}, 'HoverEnter': {'RHand(Direct)': 0, 'LHand(DIrect)': 0, 'times': 0}, 'SelectEnter': {'RHand(Direct)': 0, 'LHand(DIrect)': 0, 'times': 0}, 'SelectExit': {'RHand(Direct)': 1, 'LHand(DIrect)': 0, 'times': 1}}}, {'Chick_Word3': {'HoverExit': {'RHand(Direct)': 12, 'LHand(DIrect)': 2, 'times': 14}, 'HoverEnter': {'RHand(Direct)': 10, 'LHand(DIrect)': 4, 'times': 14}, 'SelectEnter': {'RHand(Direct)': 0, 'LHand(DIrect)': 0, 'times': 0}, 'SelectExit': {'RHand(Direct)': 7, 'LHand(DIrect)': 0, 'times': 7}}}, {'Vintage_Word8': {'HoverExit': {'RHand(Direct)': 5, 'LHand(DIrect)': 4, 'times': 9}, 'HoverEnter': {'RHand(Direct)': 3, 'LHand(DIrect)': 3, 'times': 6}, 'SelectEnter': {'RHand(Direct)': 0, 'LHand(DIrect)': 0, 'times': 0}, 'SelectExit': {'RHand(Direct)': 1, 'LHand(DIrect)': 0, 'times': 1}}}, {'Acorn_Word1': {'HoverExit': {'RHand(Direct)': 9, 'LHand(DIrect)': 0, 'times': 9}, 'HoverEnter': {'RHand(Direct)': 9, 'LHand(DIrect)': 0, 'times': 9}, 'SelectEnter': {'RHand(Direct)': 0, 'LHand(DIrect)': 0, 'times': 0}, 'SelectExit': {'RHand(Direct)': 9, 'LHand(DIrect)': 0, 'times': 9}}}, {'Charcoal_Word7': {'HoverExit': {'RHand(Direct)': 3, 'LHand(DIrect)': 2, 'times': 5}, 'HoverEnter': {'RHand(Direct)': 3, 'LHand(DIrect)': 2, 'times': 5}, 'SelectEnter': {'RHand(Direct)': 0, 'LHand(DIrect)': 0, 'times': 0}, 'SelectExit': {'RHand(Direct)': 3, 'LHand(DIrect)': 2, 'times': 5}}}]
# data_list_tanakaA = [{'Slate_Word4': {'HoverExit': {'RHand(Direct)': 20, 'LHand(DIrect)': 0, 'times': 20}, 'HoverEnter': {'RHand(Direct)': 18, 'LHand(DIrect)': 2, 'times': 20}, 'SelectEnter': {'RHand(Direct)': 0, 'LHand(DIrect)': 0, 'times': 0}, 'SelectExit': {'RHand(Direct)': 12, 'LHand(DIrect)': 0, 'times': 12}}}, {'Booze_Word8': {'HoverExit': {'RHand(Direct)': 8, 'LHand(DIrect)': 5, 'times': 13}, 'HoverEnter': {'RHand(Direct)': 7, 'LHand(DIrect)': 5, 'times': 12}, 'SelectEnter': {'RHand(Direct)': 0, 'LHand(DIrect)': 0, 'times': 0}, 'SelectExit': {'RHand(Direct)': 2, 'LHand(DIrect)': 0, 'times': 2}}}, {'Persimmon_Word1': {'HoverExit': {'RHand(Direct)': 6, 'LHand(DIrect)': 4, 'times': 10}, 'HoverEnter': {'RHand(Direct)': 8, 'LHand(DIrect)': 2, 'times': 10}, 'SelectEnter': {'RHand(Direct)': 0, 'LHand(DIrect)': 0, 'times': 0}, 'SelectExit': {'RHand(Direct)': 6, 'LHand(DIrect)': 0, 'times': 6}}}, {'Talisman_Word10': {'HoverExit': {'RHand(Direct)': 5, 'LHand(DIrect)': 0, 'times': 5}, 'HoverEnter': {'RHand(Direct)': 5, 'LHand(DIrect)': 0, 'times': 5}, 'SelectEnter': {'RHand(Direct)': 0, 'LHand(DIrect)': 0, 'times': 0}, 'SelectExit': {'RHand(Direct)': 5, 'LHand(DIrect)': 0, 'times': 5}}}, {'Canine_Word3': {'HoverExit': {'RHand(Direct)': 8, 'LHand(DIrect)': 4, 'times': 12}, 'HoverEnter': {'RHand(Direct)': 9, 'LHand(DIrect)': 3, 'times': 12}, 'SelectEnter': {'RHand(Direct)': 0, 'LHand(DIrect)': 0, 'times': 0}, 'SelectExit': {'RHand(Direct)': 6, 'LHand(DIrect)': 2, 'times': 8}}}, {'Snail_Word2': {'HoverExit': {'RHand(Direct)': 9, 'LHand(DIrect)': 3, 'times': 12}, 'HoverEnter': {'RHand(Direct)': 9, 'LHand(DIrect)': 3, 'times': 12}, 'SelectEnter': {'RHand(Direct)': 0, 'LHand(DIrect)': 0, 'times': 0}, 'SelectExit': {'RHand(Direct)': 8, 'LHand(DIrect)': 3, 'times': 11}}}, {'Crate_Word6': {'HoverExit': {'RHand(Direct)': 7, 'LHand(DIrect)': 2, 'times': 9}, 'HoverEnter': {'RHand(Direct)': 6, 'LHand(DIrect)': 2, 'times': 8}, 'SelectEnter': {'RHand(Direct)': 0, 'LHand(DIrect)': 0, 'times': 0}, 'SelectExit': {'RHand(Direct)': 4, 'LHand(DIrect)': 0, 'times': 4}}}, {'Pottery_Word5': {'HoverExit': {'RHand(Direct)': 19, 'LHand(DIrect)': 2, 'times': 21}, 'HoverEnter': {'RHand(Direct)': 16, 'LHand(DIrect)': 5, 'times': 21}, 'SelectEnter': {'RHand(Direct)': 0, 'LHand(DIrect)': 0, 'times': 0}, 'SelectExit': {'RHand(Direct)': 14, 'LHand(DIrect)': 0, 'times': 14}}}, {'Fluff_Word7': {'HoverExit': {'RHand(Direct)': 4, 'LHand(DIrect)': 2, 'times': 6}, 'HoverEnter': {'RHand(Direct)': 4, 'LHand(DIrect)': 2, 'times': 6}, 'SelectEnter': {'RHand(Direct)': 0, 'LHand(DIrect)': 0, 'times': 0}, 'SelectExit': {'RHand(Direct)': 4, 'LHand(DIrect)': 2, 'times': 6}}}, {'Fungus_Word9': {'HoverExit': {'RHand(Direct)': 3, 'LHand(DIrect)': 0, 'times': 3}, 'HoverEnter': {'RHand(Direct)': 1, 'LHand(DIrect)': 0, 'times': 1}, 'SelectEnter': {'RHand(Direct)': 0, 'LHand(DIrect)': 0, 'times': 0}, 'SelectExit': {'RHand(Direct)': 1, 'LHand(DIrect)': 0, 'times': 1}}}]
# data_list = [{'Carving_Word5': {'HoverExit': {'RHand(Direct)': 13, 'LHand(DIrect)': 12, 'times': 25}, 'HoverEnter': {'RHand(Direct)': 13, 'LHand(DIrect)': 12, 'times': 25}, 'SelectEnter': {'RHand(Direct)': 0, 'LHand(DIrect)': 0, 'times': 0}, 'SelectExit': {'RHand(Direct)': 11, 'LHand(DIrect)': 0, 'times': 11}}}, {'Granite_Word4': {'HoverExit': {'RHand(Direct)': 5, 'LHand(DIrect)': 2, 'times': 7}, 'HoverEnter': {'RHand(Direct)': 5, 'LHand(DIrect)': 2, 'times': 7}, 'SelectEnter': {'RHand(Direct)': 0, 'LHand(DIrect)': 0, 'times': 0}, 'SelectExit': {'RHand(Direct)': 5, 'LHand(DIrect)': 0, 'times': 5}}}, {'Decor_Word10': {'HoverExit': {'RHand(Direct)': 8, 'LHand(DIrect)': 2, 'times': 10}, 'HoverEnter': {'RHand(Direct)': 8, 'LHand(DIrect)': 2, 'times': 10}, 'SelectEnter': {'RHand(Direct)': 0, 'LHand(DIrect)': 0, 'times': 0}, 'SelectExit': {'RHand(Direct)': 10, 'LHand(DIrect)': 0, 'times': 10}}}, {'Garland_Word6': {'HoverExit': {'RHand(Direct)': 8, 'LHand(DIrect)': 8, 'times': 16}, 'HoverEnter': {'RHand(Direct)': 9, 'LHand(DIrect)': 7, 'times': 16}, 'SelectEnter': {'RHand(Direct)': 0, 'LHand(DIrect)': 0, 'times': 0}, 'SelectExit': {'RHand(Direct)': 5, 'LHand(DIrect)': 2, 'times': 7}}}, {'Ewe_Word2': {'HoverExit': {'RHand(Direct)': 21, 'LHand(DIrect)': 11, 'times': 32}, 'HoverEnter': {'RHand(Direct)': 23, 'LHand(DIrect)': 9, 'times': 32}, 'SelectEnter': {'RHand(Direct)': 0, 'LHand(DIrect)': 0, 'times': 0}, 'SelectExit': {'RHand(Direct)': 7, 'LHand(DIrect)': 5, 'times': 12}}}, {'Dandelion_Word9': {'HoverExit': {'RHand(Direct)': 4, 'LHand(DIrect)': 0, 'times': 4}, 'HoverEnter': {'RHand(Direct)': 1, 'LHand(DIrect)': 0, 'times': 1}, 'SelectEnter': {'RHand(Direct)': 0, 'LHand(DIrect)': 0, 'times': 0}, 'SelectExit': {'RHand(Direct)': 1, 'LHand(DIrect)': 0, 'times': 1}}}, {'Chick_Word3': {'HoverExit': {'RHand(Direct)': 19, 'LHand(DIrect)': 3, 'times': 22}, 'HoverEnter': {'RHand(Direct)': 18, 'LHand(DIrect)': 4, 'times': 22}, 'SelectEnter': {'RHand(Direct)': 0, 'LHand(DIrect)': 0, 'times': 0}, 'SelectExit': {'RHand(Direct)': 12, 'LHand(DIrect)': 0, 'times': 12}}}, {'Vintage_Word8': {'HoverExit': {'RHand(Direct)': 5, 'LHand(DIrect)': 1, 'times': 6}, 'HoverEnter': {'RHand(Direct)': 2, 'LHand(DIrect)': 1, 'times': 3}, 'SelectEnter': {'RHand(Direct)': 0, 'LHand(DIrect)': 0, 'times': 0}, 'SelectExit': {'RHand(Direct)': 1, 'LHand(DIrect)': 0, 'times': 1}}}, {'Acorn_Word1': {'HoverExit': {'RHand(Direct)': 14, 'LHand(DIrect)': 15, 'times': 29}, 'HoverEnter': {'RHand(Direct)': 17, 'LHand(DIrect)': 11, 'times': 28}, 'SelectEnter': {'RHand(Direct)': 0, 'LHand(DIrect)': 0, 'times': 0}, 'SelectExit': {'RHand(Direct)': 14, 'LHand(DIrect)': 4, 'times': 18}}}, {'Charcoal_Word7': {'HoverExit': {'RHand(Direct)': 4, 'LHand(DIrect)': 4, 'times': 8}, 'HoverEnter': {'RHand(Direct)': 4, 'LHand(DIrect)': 4, 'times': 8}, 'SelectEnter': {'RHand(Direct)': 0, 'LHand(DIrect)': 0, 'times': 0}, 'SelectExit': {'RHand(Direct)': 4, 'LHand(DIrect)': 3, 'times': 7}}}]
# data_list = [{'Slate_Word4': {'HoverExit': {'RHand(Direct)': 10, 'LHand(DIrect)': 0, 'times': 10}, 'HoverEnter': {'RHand(Direct)': 10, 'LHand(DIrect)': 0, 'times': 10}, 'SelectEnter': {'RHand(Direct)': 0, 'LHand(DIrect)': 0, 'times': 0}, 'SelectExit': {'RHand(Direct)': 6, 'LHand(DIrect)': 0, 'times': 6}}}, {'Booze_Word8': {'HoverExit': {'RHand(Direct)': 8, 'LHand(DIrect)': 2, 'times': 10}, 'HoverEnter': {'RHand(Direct)': 4, 'LHand(DIrect)': 2, 'times': 6}, 'SelectEnter': {'RHand(Direct)': 5, 'LHand(DIrect)': 0, 'times': 5}, 'SelectExit': {'RHand(Direct)': 4, 'LHand(DIrect)': 1, 'times': 5}}}, {'Persimmon_Word1': {'HoverExit': {'RHand(Direct)': 8, 'LHand(DIrect)': 0, 'times': 8}, 'HoverEnter': {'RHand(Direct)': 7, 'LHand(DIrect)': 1, 'times': 8}, 'SelectEnter': {'RHand(Direct)': 0, 'LHand(DIrect)': 0, 'times': 0}, 'SelectExit': {'RHand(Direct)': 8, 'LHand(DIrect)': 0, 'times': 8}}}, {'Talisman_Word10': {'HoverExit': {'RHand(Direct)': 4, 'LHand(DIrect)': 2, 'times': 6}, 'HoverEnter': {'RHand(Direct)': 4, 'LHand(DIrect)': 2, 'times': 6}, 'SelectEnter': {'RHand(Direct)': 0, 'LHand(DIrect)': 0, 'times': 0}, 'SelectExit': {'RHand(Direct)': 4, 'LHand(DIrect)': 0, 'times': 4}}}, {'Canine_Word3': {'HoverExit': {'RHand(Direct)': 13, 'LHand(DIrect)': 1, 'times': 14}, 'HoverEnter': {'RHand(Direct)': 12, 'LHand(DIrect)': 3, 'times': 15}, 'SelectEnter': {'RHand(Direct)': 0, 'LHand(DIrect)': 0, 'times': 0}, 'SelectExit': {'RHand(Direct)': 6, 'LHand(DIrect)': 0, 'times': 6}}}, {'Snail_Word2': {'HoverExit': {'RHand(Direct)': 6, 'LHand(DIrect)': 0, 'times': 6}, 'HoverEnter': {'RHand(Direct)': 6, 'LHand(DIrect)': 0, 'times': 6}, 'SelectEnter': {'RHand(Direct)': 0, 'LHand(DIrect)': 0, 'times': 0}, 'SelectExit': {'RHand(Direct)': 6, 'LHand(DIrect)': 0, 'times': 6}}}, {'Crate_Word6': {'HoverExit': {'RHand(Direct)': 3, 'LHand(DIrect)': 0, 'times': 3}, 'HoverEnter': {'RHand(Direct)': 3, 'LHand(DIrect)': 0, 'times': 3}, 'SelectEnter': {'RHand(Direct)': 0, 'LHand(DIrect)': 0, 'times': 0}, 'SelectExit': {'RHand(Direct)': 2, 'LHand(DIrect)': 0, 'times': 2}}}, {'Pottery_Word5': {'HoverExit': {'RHand(Direct)': 9, 'LHand(DIrect)': 2, 'times': 11}, 'HoverEnter': {'RHand(Direct)': 7, 'LHand(DIrect)': 4, 'times': 11}, 'SelectEnter': {'RHand(Direct)': 0, 'LHand(DIrect)': 0, 'times': 0}, 'SelectExit': {'RHand(Direct)': 7, 'LHand(DIrect)': 0, 'times': 7}}}, {'Fluff_Word7': {'HoverExit': {'RHand(Direct)': 3, 'LHand(DIrect)': 3, 'times': 6}, 'HoverEnter': {'RHand(Direct)': 3, 'LHand(DIrect)': 3, 'times': 6}, 'SelectEnter': {'RHand(Direct)': 0, 'LHand(DIrect)': 0, 'times': 0}, 'SelectExit': {'RHand(Direct)': 3, 'LHand(DIrect)': 1, 'times': 4}}}, {'Fungus_Word9': {'HoverExit': {'RHand(Direct)': 4, 'LHand(DIrect)': 1, 'times': 5}, 'HoverEnter': {'RHand(Direct)': 0, 'LHand(DIrect)': 0, 'times': 0}, 'SelectEnter': {'RHand(Direct)': 3, 'LHand(DIrect)': 0, 'times': 3}, 'SelectExit': {'RHand(Direct)': 0, 'LHand(DIrect)': 0, 'times': 0}}}]

# table(data_list)
#